### ISSUE TITLE
Include generation capacity?

### ISSUE THREAD

**Issue by gwpicard** [carbon-data-specification/Power-Systems-Data#18]
Should we include information about zone capacity in the data model?
Depending on the granularity, we could specify capacity anywhere from say plant-->bidding zone level.
Regardless, this should probably be broken down by production / generation mode / fuel type

**Comment by gwpicard** [comment]
@m-mirz what are your thoughts here?

**Comment by Henry-WattTime** [comment]
Seems like a great idea, should it be by unit? I think it could be added to the 'static data' section.

**Comment by gwpicard** [comment]
Given the level of granularity we're exploring, I think that per-unit is a good idea.

**Comment by m-mirz** [comment]
@gwpicard I agree. Yes, per unit would be great!

**Comment by m-mirz** [comment]
@gwpicard I think this is also related to @halliecramer1 's input here #23.
@gwpicard and @Henry-WattTime maybe we can merge #15 and #23.

**Comment by gwpicard** [comment]
This is included in the workstream 2 spreadsheet
https://docs.google.com/spreadsheets/d/1ZDYFBX3InzNi4Kwr5_enBc40BwvEnYihd9w0zCr40Uc/edit#gid=0
We can probably close.
