### ISSUE TITLE
New working group structure

### ISSUE THREAD

**Issue by gwpicard** [carbon-data-specification/Power-Systems-Data#28]
After last week's meeting, and a sync with Markus, we are going to move ahead with more of an organised structure with work streams to enable more concrete progress with better defined deliverables.

The working group will be split into three workstreams with the following goals:
1. Topology / graph model workstream
    - **End deliverable:** The topological graph model that will be used for the data. The model is an abstract description of a grid and can be applied across any grid configuration (market + location agnostic model). 
    - Questions to answer:
        - What and how many levels of abstraction should we use?
        - How does it map to CIM/CGMES?
        - ...
    - Relevant issues:
        - #4
        - #24 

2. Data types + specifications workstream
     - **End deliverable:** A comprehensive list of all data types/kinds needed in the model, as well as the respective properties (dynamic/static, etc.). 
    - Questions to answer:
        - How many data types should we specify?
        - How do we split up and define the data types?
        - What is the right level of granularity?
        - When / how should we include carbon data (if any)?
        - ...
    - Relevant issues:
        - #21
        - #18 
        - #8
        - #7 
        - #6 
        - #5
3. Data interfacing workstream
     - **End deliverable:** A fully-defined API (interface) spec that describes how to get data from the data, and what data should be served by each request. 
    - Questions to answer:
        - Is it flexible / intuitive enough for adopters e.g. TSOs?
        - How many endpoints should we specify?
        - What is the best interface (Rest API, GraphQL...)?
        - How do we aggregate?
        - How does the interface deal with missing values?
        - ...
    - Relevant issues:
        - #21
        - #25
        - #19 
        - #22 
        - #3

**Working principles**
- Each group will have a main driver, who will be responsible for:
     1. Ensuring progress and getting others in the workstream to provide input and contribute
     2. Coordinating with the other workstream where relevant
     3. Keep their issues cleaned up in GitHub
     4. Presenting updates from the workstream at the biweekly sync
- Someone from each workstream familiar with GitHub will be responsible for creating the relevant pull requests. The main driver will make sure everyone can contribute to progress, including those unfamiliar with GitHub (best through GitHub issues, if not at the very least documents linked back to a GitHub issue).
- The biweekly meeting will focus solely on agreeing on pull request scopes and content (having gathered all the input). Little focus should be given to the issues themselves (discussion should ideally happen async/outside of biweekly meeting).

**Comment by gwpicard** [comment]
We'll start by having workstream 1 + 2 kicking off in parallel, and then once they join, the working group will transition to working on 3 to tie everything together.

Ideal timeline:
~1 month for workstreams 1 and 2, then aggregate work. Do another pass depending on state of work after the month.
~2 weeks-1 month for workstream 3

Suggested drivers:
1. **Driver:** Greg Miller
2. **Driver:** Henry Richardson
3. **Driver:** Guillaume Picard

We can discuss the best participants at the meeting (I don't have a list)

**Comment by gwpicard** [comment]
@m-mirz fyi

**Comment by m-mirz** [comment]
I have cleaned up the existing PRs and created a new one for the workstream files @gwpicard, see #29.

**Comment by gwpicard** [comment]
> I have cleaned up the existing PRs and created a new one for the workstream files @gwpicard, see #29.

Great, thanks!

**Comment by m-mirz** [comment]
@gwpicard and @Henry-WattTime agreed to take the driver roles for workstream 2 and 3 for now. Reaching out to @grgmiller asynchronously.

**Comment by m-mirz** [comment]
Please indicate where each of you wants to participate below.

**Comment by m-mirz** [comment]
My focus will be workstream 1.

**Comment by gwpicard** [comment]
I will lead workstream 3, and keep updated on workstream 1 and 2 to make sure I'm following the overall progress.

**Comment by pierresegonne** [comment]
Closing this as I added that information in the wiki
