### ISSUE TITLE
What datasets are still missing

### ISSUE THREAD

**Issue by m-mirz** [carbon-data-specification/Power-Systems-Data#6]
- curtailment for wind, solar
- market data
- there is static and dynamic data
- when do we ex

**Comment by m-mirz** [comment]
PR #11 is addressing this issue.

**Comment by gwpicard** [comment]
Closing as points now captured in spreadsheet:
https://docs.google.com/spreadsheets/d/1ZDYFBX3InzNi4Kwr5_enBc40BwvEnYihd9w0zCr40Uc/edit#gid=0
