### ISSUE TITLE
Review the Common information model (CIM)

### ISSUE THREAD

**Issue by pierresegonne** [carbon-data-specification/Power-Systems-Data#64]
People at ENTSO-E have recommended us to look at the CIM which is used across power system operators. 

It would make sense to verify that our specifications follow or at least resemble their taxonomy. 

https://www.entsoe.eu/digital/common-information-model/

**Comment by ssuffian** [comment]
This documentation seems to be the best place to navigate the different objects in the CIM: https://ontology.tno.nl/IEC_CIM/

**Comment by m-mirz** [comment]
These resources might be helpful as well
http://sogno.energy/libcimpp/IEC61970_16v29a/annotated.html
https://github.com/sogno-platform/cimpy
https://sogno.energy/cimpy/cimpy.cgmes_v2_4_15.html
