### ISSUE TITLE
Fix adhoc items before LFE summit

### ISSUE THREAD

**Issue by pierresegonne** [carbon-data-specification/Power-Systems-Data#66]
**Website**:

* Minutes link at bottom returns 404 not found
* Can we add links to the actual specifications? Versions I believe are out of date
* Still references strategy committee / technical steering committee - should remove and add reference to LFESS (see CDSC landing page for guidance)
* Missing link to other working group

**Github**:

* Specifications folder is empty
* There's a specifications template that doesn't appear to be used - I can check to see whether this format is needed to get specs approved
* Remove timestamp format info from data interface md file?
* Topology file has some empty columns and question marks - should we fill these in or remove? 
* Can we add some documentation in the README to explain how the three different specs work together?

**Comment by ssuffian** [comment]
I've started working on this, I should have a PR relatively soon
