### ISSUE TITLE
Granularity of production and consumption

### ISSUE THREAD

**Issue by m-mirz** [carbon-data-specification/Power-Systems-Data#7]
- specify fuel types etc.
- distribution or transmission network level

**Comment by halliecramer1** [comment]
Started drafting here: https://docs.google.com/spreadsheets/d/1SBPr7dIX-obQGryarmWcjo6X6C9s4rFt2lix_vi20p4/edit#gid=326977865

Three classifiers are: Class, Fuel Type, Technology Type
Sub-class is then the combination of class + fuel type + technology type

**Comment by m-mirz** [comment]
I am working on the MD version for this. Here's the MD for the first table...

Class | Fuel | Technology | Sub-Class
-- | -- | -- | --
Biomass | Brown coal/Lignite | Energy Storage, Battery | Class + Technology + Fuel
Fossil | Hard coal | Energy Storage, Compressed Air |  
Geothermal | Coal-derived gas | Energy Storage, Concentrated Solar Power |  
Hydro | Other coal | Energy Storage, Flywheel |  
Marine | Natural gas | Energy Storage, Reversible Hydraulic Turbine |  
Nuclear | Landfill gas | Energy Storage, Other |  
Other renewable | Other gas | Fuel Cell |  
Solar | Wood / Wood waste | Turbine, Binary Cycle |  
Waste | Municipal waste | Turbine, Combined-Cycle |  
Wind | Propane oil | Turbine, Steam |  
Other non-renewable | Shale oil | Turbine, Gas Combustion |  
Storage Discharge | Distillate oil | Hydrokinetic, Axial Flow Turbine |  
| | Other oil | Hydrokinetic, Wave Buoy |  
| | Peat | Hydrokinectic, Other |  
| | Uranium, Thorium, Plutonium | Hydraulic Turbine |  
| | Solar | Internal Combustion |  
| | Wind | Other |  
| | Geothermal | Photovoltaic |  
| | Water | Wind Turbine, Onshore |  
| | | Wind Turbine, Offshore |

**Comment by m-mirz** [comment]
Draft of second table...

Data Field | Description (initial draft from ENTSOE Detailed Data Descriptions) | Aggregation Levels | Latency
-- | -- | -- | --
Actual Generation | Actual aggregated Net generation output (MW) per market time unit, per zone and per production type. | Inputs: Time range, Time zoneProduction type options: sub-class, classTemporal options: 5 min, 15 min, 1 hr, or totalLocational options: grid, zonal, distribution-level | Hour +1
Actual Interchange | Actual aggregated Net interchange (MW) per market time unit, per zone and per imports and exports. | Inputs: Time range, Time zone, imports, exports, net importsTemporal options: 5 min, 15 min, 1 hr, or totalLocational options: by interconnect, total | Day +7
Actual Curtailment | Actual aggregated curtailment (MW) per market time unit, per zone and per production type. | Inputs: Time range, Time zoneProduction type options: sub-class, class Temporal options: 5 min, 15 min, 1 hr, or totalLocational options: grid, zonal | Hour +1
Actual Load | Actual total load per zone per market time unit, the total load being defined as equal to the sum of power generated by plants on both TSO/DSO networks, from which the following is deduced:- the balance (export-import) of exchanges on interconnections between neighbouring bidding zones.- the power absorbed by energy storage resources. | Inputs: Time range, Time zoneTemporal options: 5 min, 15 min, 1 hr, or totalLocational options: grid, zonal | Hour +1
Forecast Generation | An estimate of the total scheduled Net generation (MW) per zone, per each market time unit of the following day. | Production type options: sub-class, classTemporal options: 5 min, 15 min, 1 hr, or totalLocational options: grid, zonal, distribution-level | Day ahead, real-time
Forecast Curtailment | An estimate of the total curtailment (MW) per market time unit, per zone and per production type. | By production type (wind + solar classes) | Day ahead, real-time
Forecast Load | A day-ahead forecast of the total load per market time unit per bidding zone at the latest two hours before the gate closure time of the day-ahead market in the bidding zone or at D-1, 12:00 in local time zone of the bidding zone at the latest when gate closure time does not apply. The day-ahead forecast has to be updated, if there are major changes. A major change represents a change of at least 10% of the total load forecast in one market time unit. | By load zone, grid-level | Day ahead, real-time
Locational Marginal Price | For every market time unit the day-ahead and real-time prices in each bidding zone (Currency/MWh). | By hub, zone, node | Day ahead, real-time
Installed Capacity | The sum of installed Net generation capacity (MW) per control area for all existing production units equaling to or exceeding 1 MW installed generation capacity, per production type. | By production type | Annual
Heat Rate | The amount of energy used by an electrical generator/power plant to generate one kilowatthour (kWh) of electricity. | By fuel + technology type | Annual

**Comment by m-mirz** [comment]
We discussed that the columns should be in separate tables or a bullet point list would also be fine.

**Comment by m-mirz** [comment]
I converted the first table to bullet points and added the descriptions on this branch: https://github.com/carbon-data-specification/Power-Systems-Data/tree/production-consumption

**Comment by m-mirz** [comment]
Maybe we should split the first section, bullet points, and the second section, the table, into two PRs? I think the bullet point list looks already quite good.
