### ISSUE TITLE
Look into the relationship between fuel types and generation technologies

### ISSUE THREAD

**Issue by ssuffian** [carbon-data-specification/Power-Systems-Data#72]
Fuel types and generation technologies are separately enumerated [here](https://www.aib-net.org/sites/default/files/assets/eecs/facts-sheets/AIB-2019-EECSFS-05%20EECS%20Rules%20Fact%20Sheet%2005%20-%20Types%20of%20Energy%20Inputs%20and%20Technologies%20-%20Release%207.7%20v5.pdf), but some discussion took place in the working group meeting that we may want to have some sort of combined relationship in order to more accurately calculate carbon intensity numbers. This is particularly important for natural gas.

We should look into some of the other standards to see how they deal with this relationship.

**Comment by Henry-WattTime** [comment]
I did a quick survey of a few sources just to see what folks are doing around the world, see below for a quick summary. After thinking through this in more detail, it seems that both fuel and technology are very important, maybe we should adopt the AIB approach for both? What do folks think?

AIB, European Energy Certificate System
https://www.aib-net.org/sites/default/files/assets/eecs/facts-sheets/AIB-2019-EECSFS-05%20EECS%20Rules%20Fact%20Sheet%2005%20-%20Types%20of%20Energy%20Inputs%20and%20Technologies%20-%20Release%207.7%20v5.pdf
Separates fuel and technology
Has a hierarchy for both fuel and technology, multiple levels

EPA eGRID 
(https://www.epa.gov/egrid)
Splits it into “prime mover” (the generation technology) and “primary fuel” (fuel combusted) at the unit, generator, and plant level. Also defines levels within the fuels and technologies
Technology not reported at higher levels of aggregation
Very detailed codes for both categories: https://www.epa.gov/system/files/documents/2023-01/eGRID2021_technical_guide.pdf

EIA Hourly Electric Grid Monitor 
(https://www.eia.gov/electricity/gridmonitor/dashboard/electric_overview/US48/US48)
Only reports fuel type by region, no technology reported

ENTSO-E
(https://transparency.entsoe.eu/generation/r2/actualGenerationPerProductionType/show)
Fuel broken out by sub-category, no technology

Semi-random sampling of grids:

UK Balancing Mechanism Report
(https://www.bmreports.com/bmrs/?q=generation/fueltype)
ACTUAL GENERATION - BY FUEL TYPE (in MW) reported by fuel, except gas is split into combined cycled and open cycle and hydro is pumped storage and hydro. 

ERCOT
(https://www.ercot.com/gridmktinfo/dashboards/fuelmix)
No technology reported, only fuel. 
“The Natural Gas category is comprised of Gas Steam, Simple Cycle, Combined Cycle, and Reciprocating Engine resources and may also include resources that use diesel or fuel oil.”

Japan:
(https://www.renewable-ei.org/en/statistics/electricity/#demand)
Combines all fossil generation into a single thermal category, no differentiation by fuel type or technology

**Comment by ssuffian** [comment]
For the time being, we have decided to adopt the AIB standard. We can discuss alternative standards going forward.
